[package]
name = "pyscramble"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyscramble"
crate-type = ["cdylib"]

[dependencies]
md-5 = "0.10.6"
numpy = "0.27.1"
pyo3 = "0.27.0"
